### ISSUE TITLE
Cannot update datasources

### ISSUE THREAD

**Issue by cruisemaniac** [kwery/kwery#10]
When I try to change the saved data pertaining to a datasource, I get an error: `Something went wrong, please check Kwery server log`.

Kwery log has the following:
```
12:07:15.797 [qtp863125040-11] INFO  c.k.s.datasource.DatasourceService - Successfully connected to MYSQL datasource 1.2.3.4 with label Production Slave
12:07:15.861 [qtp863125040-11] WARN  o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: 20000, SQLState: 23505
12:07:15.861 [qtp863125040-11] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'UC_SQL_QUERY_ID_FK_JOB_ID_FK' defined on 'JOB_SQL_QUERY'.
12:07:15.861 [qtp863125040-11] INFO  o.h.e.j.b.internal.AbstractBatchImpl - HHH000010: On release of batch it still contained JDBC statements
12:07:15.864 [qtp863125040-11] ERROR ninja.NinjaDefault - Emitting bad request 500. Something really wrong when calling route: /api/datasource/add-datasource (class: class com.kwery.controllers.apis.DatasourceApiController method: public ninja.Result com.kwery.controllers.apis.DatasourceApiController.addDatasource(com.kwery.models.Datasource,ninja.Context,ninja.validation.Validation))
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692) ~[kwery-1.9.6.jar:na]
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602) ~[kwery-1.9.6.jar:na]
	at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:492) ~[kwery-1.9.6.jar:na]
	at org.hibernate.jpa.criteria.compile.CriteriaQueryTypeQueryAdapter.getResultList(CriteriaQueryTypeQueryAdapter.java:50) ~[kwery-1.9.6.jar:na]
	at com.kwery.dao.JobDao.filterJobs(JobDao.java:115) ~[kwery-1.9.6.jar:na]
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:62) ~[kwery-1.9.6.jar:na]
	at com.kwery.dao.DatasourceDao.update(DatasourceDao.java:50) ~[kwery-1.9.6.jar:na]
	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:70) ~[kwery-1.9.6.jar:na]
	at com.kwery.controllers.apis.DatasourceApiController.addDatasource(DatasourceApiController.java:109) ~[kwery-1.9.6.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at ninja.params.ControllerMethodInvoker.invoke(ControllerMethodInvoker.java:57) ~[kwery-1.9.6.jar:na]
	at ninja.FilterChainEnd.next(FilterChainEnd.java:49) ~[kwery-1.9.6.jar:na]
	at com.kwery.filters.DashRepoSecureFilter.filter(DashRepoSecureFilter.java:23) ~[kwery-1.9.6.jar:na]
	at ninja.FilterChainImpl.next(FilterChainImpl.java:35) ~[kwery-1.9.6.jar:na]
	at ninja.NinjaDefault.onRouteRequest(NinjaDefault.java:102) ~[kwery-1.9.6.jar:na]
	at ninja.servlet.NinjaServletDispatcher.service(NinjaServletDispatcher.java:86) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:287) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:277) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:182) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [kwery-1.9.6.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [kwery-1.9.6.jar:na]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [kwery-1.9.6.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by abhirama** [comment]
Fixed in release v2.0.2.
